### ISSUE TITLE
Errors when generating nuts with threads on OCC 7.2

### ISSUE THREAD

**Issue by shaise** [ulrich1a/screw_maker#1]
Hi Ulrich,

It looks like in OCC7.2 (FreeCad 0.17 release & up), some nuts can not generate real threads. For example Nut Iso4032 M5. The following error happens:

`Traceback (most recent call last):
  File "C:/Users/shaise/Documents/Personal/freecad/FreeCAD_Macros/screw_maker2_3.py", line 1973, in guiCreateScrew
    myObj = self.theScrew.createScrew(ST_text, ND_text, NL_text, threadType)
  File "C:/Users/shaise/Documents/Personal/freecad/FreeCAD_Macros/screw_maker2_3.py", line 2382, in createScrew
    screw = self.makeIso4032(ST_text, ND_text)
  File "C:/Users/shaise/Documents/Personal/freecad/FreeCAD_Macros/screw_maker2_3.py", line 4871, in makeIso4032
    nutShell = Part.Shell(nutFaces)
Part.OCCError: Shape is not a shell
`

**Comment by luzpaz** [comment]
@shaise is this obsolete now? (currrently at OCC 7.5.1)

**Comment by shaise** [comment]
Generating threads still fail sporadically, but it nothing we can do or predict.
